lesson2 created1
alina-gurjeva/sql_lessons pull request #1
Opened 2021-03-07 13:58 UTC by alina-gurjeva

2021-03-08 14:34 UTC, tigal requested changes
Привет! Все хорошо, есть небольшая ошибка в синтаксисе и потеряна инструкция.
Везде оставила комментарии, в том числе на вопросы ответила:)

Жду тогда исправлений по небольшим ошибкам (напиши в ЛС пожалуйста, как исправишь, пока оценку не ставлю), 4 задание у нас по желанию, если придумаешь решение - супер.

2021-03-08 14:34 UTC, tigal commented on task2.sql
> +)
Не хватает ; в конце инструкции

2021-03-08 14:34 UTC, tigal commented on task3.txt
> +Этой командой создавала dump. Оказывается, PowerShell Windows не может корректно работать со знаками < и >.
Нужно как раз cmd использовать, power shell нам не нужен:)

2021-03-08 14:34 UTC, tigal commented on task3.txt
> +mysql sample < sample1.sql
Забыли добавить команду создания базы данных sample, если развернуть без создания БД вылетит ошибка

2021-03-08 14:34 UTC, tigal commented on task4.TXT
> +Решение так и не нашла, в том числе пыталась внутри mysql создать базу данных, а в ней таблицу с соотвествующим названием - получала ошибку  Table 'copy_hp.help_keyword' doesn't exist
Применять дамп не нужно:) mysql - это зарезервированная база данных самим MySQL, также как и ее таблички. То есть их нельзя удалить, например, а также создать новую таблицу в базе данных mysql. Лучше вообще эту базу совсем не трогать, только select оттуда делать

Так что вы делаете все правильно, но MySQL просто запрещает эти действия для этой базы и таблицы.
Как вы можете по вашему дампу посмотреть, он создался по тем условиям, которые вы ему указали как раз (hp.sql)

2021-03-08 14:34 UTC, tigal commented on task4.TXT
> +mysqldump --where="true limit 100" mysql help_keyword > hp.sql
Практически правильно, но забыли одного условие - должны быть ПЕРВЫЕ 100 строк. То есть строки со значениями help_keyword_id от 0 до 100 (по возрастанию). 
У вас в дампе получаются 100 случайных строк, можете посмотреть в hp.sql.
Подумайте, как можно изменить условие:)

2021-03-08 19:15 UTC, alina-gurjeva commented on task3.txt
> +mysql sample < sample1.sql
Да, я ее делала (на скрине видно, что база без проблем отобразилась) - но в задании забыла указать ) Поправила

2021-03-08 19:16 UTC, alina-gurjeva commented on task4.TXT
> +Решение так и не нашла, в том числе пыталась внутри mysql создать базу данных, а в ней таблицу с соотвествующим названием - получала ошибку  Table 'copy_hp.help_keyword' doesn't exist
Попробовала применить обходное решение) Изменила файлы)

2021-03-09 08:55 UTC, tigal commented
По исправлениям все отлично:)
По четвертому заданию: очень интересный вариант решения, когда не знаете, как поменять инструкции mysqldump.
Лучше было бы в данном случае целиком скопировать структуру таблицы из файла hp.sql. Тогда прямо один в один вышло бы:)
Если бы стояла такая рабочая задача - вы отлично подошли к ее решению и выполнили ее (и это самое главное), решили обходным путем:)
С точки зрения mysqldump я выложу решение в четверг по тому, как можно решить эту задачу именно с mysqldump. Оно короче и на самом деле очень похоже оказывается на ваше решение:)
Оценка за работу отлично:)

2021-03-09 11:41 UTC, merged